name: Build documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # checkout main branch
      - uses: actions/checkout@v4

      # install Python 3.11, and cache pip dependencies
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r docs/requirements.txt

      # build the website, save output to _site folder
      # which is the folder name that actions/upload-pages-artifact@v2 expects by default
      - name: Run sphinx-build
        run: sphinx-build -b html -v docs _site

      - name: Remove unneeded files
        run: rm -r _site/.doctrees _site/.buildinfo

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
